---
- name: SLES Linux OS Patching
  hosts: all
  serial: "{{ serial_number | default(10) }}"
  gather_facts: yes
  vars_files:
    - vault_pass.yml

  pre_tasks:
    - name: Ensure log directory exists
      file:
        path: /infravol/config_backup/patch_logs/error_logs
        state: directory
        mode: '0755'
      delegate_to: localhost
      run_once: true

    - name: Initialize patch status
      set_stats:
        data:
          patch_status:
            status: "running"
  tasks:
    - name: Run patching with error handling
      block:
        - name: Run RedHat patching role
          include_role:
            name: patching_redhat
          when: ansible_distribution == "RedHat"

        - name: Run SUSE patching role
          include_role:
            name: patching_suse
          when: ansible_os_family == "Suse" or ansible_distribution == "SLES"

        - name: Mark patch status as success
          set_stats:
            data:
              patch_status:
                status: "success"

      rescue:
        - name: Capture failure from role
          set_stats:
            data:
              patch_status:
                status: "failed"
                task: "{{ ansible_failed_task.name | default('Task not captured') }}"
                msg: "{{ ansible_failed_result.msg | default('No message') }}"

        - name: Log failure to file
          copy:
            content: |
              Host: {{ inventory_hostname }}
              Failed Task: {{ patch_status.task }}
              Error: {{ patch_status.msg }}
            dest: "/infravol/config_backup/patch_logs/error_logs/{{ inventory_hostname }}_role_error.log"
          delegate_to: localhost

        #- name: Mark host as failed
         # fail:
          #  msg: "Role execution failed for {{ inventory_hostname }}. See log for details."
        - name: stop execution for this host
          meta: end_host

- name: Aggregate patch results on localhost
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Initialize patch success and error lists
      set_fact:
        patch_success: []
        patch_errors: {}

    - name: Aggregate results from hosts
      set_fact:
        patch_success: "{{ patch_success + [item] if hostvars[item].patch_status.status == 'success' else patch_success }}"
        patch_errors: "{{ patch_errors | combine({ item: hostvars[item].patch_status}) if hostvars[item].patch_status == 'failed' else patch_errors }}"
      loop: "{{ groups['all'] }}"
      when:
        - item != 'localhost'
        - hostvars[item].ansible_stats is defined
        - hostvars[item].ansible_stats.data.patch_status is defined

    - name: Create patch summary content
      set_fact:
        patch_summary: |
          Patch Summary Report

          Successful Hosts:
          {% for host in patch_success %}
          - {{ host }}
          {% else %}
          None
          {% endfor %}

          Failed Hosts:
          {% for host, error in patch_errors.items() %}
          - {{ host }}: {{ error.task | default('unknown task') }} - Logs are saved at /infravol directory.
          {% else %}
          None
          {% endfor %}


    - name: Send patch summary email
      mail:
        host: "casarray1.bdx.com"
        port: 25
        secure: never
        from: "ashvani.kumar@bd.com"
        to: "ashvani.kumar@bd.com"
        subject: "Linux Patching Completed"
        body: "{{ patch_summary }}"
